import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import ReduxProvider from "../redux/ReduxProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const InterSans = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"]
// })

const MontserratSans = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  adjustFontFallback: true,
})

export const metadata: Metadata = {
  title: "Pato League",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      
      <ReduxProvider>
      <AuthProvider>
        
        <body
          className={`${MontserratSans.variable} antialiased bg-[#f0f0f0]`}
        >
          {children}
        </body>
        </AuthProvider>
      </ReduxProvider>
    </html>
  );
}
